sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t sparkbot .
  - docker run -d -p 127.0.0.1:29060:5000 --name sparkb1 sparkbot

script:
    - docker ps | grep -q sparkb1
